---
# tasks file for haproxy

- name: install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpie
    -  haproxy
  notify: restart haproxy

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart haproxy
